config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :offers, only: %i[index show new create destroy] do # Need to check "offer#destroy route"
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :bookings, only: %i[update destroy]
  resources :reviews, only: [:destroy]

  get "my_bookings", to: "pages#my_bookings", as: :my_bookings
  get "my_offers", to: "pages#my_offers", as: :my_offers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  enum status: %i[pending accepted rejected]
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :offers

  include PgSearch::Model
  multisearchable against: [:name]
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :game
  belongs_to :user
  has_many :bookings
  has_many :reviews

  include PgSearch::Model
  pg_search_scope :search_by_game_and_user,
                  against: :title,
                  associated_against: {
                    game: :name,
                    user: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  validates :rating, numericality: { only_integer: true, in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offers, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :offers, source: :bookings
  has_many :reviews, dependent: :destroy
  has_many :reviews_as_owner, through: :offers, source: :reviews
  has_one_attached :photo

  include PgSearch::Model
  multisearchable against: [:name]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new(booking_params)
    @booking.offer = @offer
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to my_offers_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to my_bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:content, :status, :date)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @offers = policy_scope(Offer).search_by_game_and_user(params[:query])
    else
      @offers = policy_scope(Offer)
    end
  end

  def show
    @offer = Offer.find(params[:id])
    authorize @offer
    @booking = Booking.new
    @other_offers = @offer.user.offers.where.not(id: @offer.id)

    filter_own_offer_reviews(@offer)
    @my_reviews = @reviews.where(user: current_user)
    @review = Review.new
  end

  def new
    # this instance is for the form
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    authorize @offer
    if @offer.save
      redirect_to my_offers_path
    else
      # render 'new.html.erb'
      # redirect_to new_restaurant_path
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.destroy
    redirect_to my_offers_path, status: :see_other
  end

  private

  # strong params -> whitelisting the attributes that the user can give us
  def offer_params
    params.require(:offer).permit(:title, :description, :duration, :price, :game_id)
  end

  def filter_own_offer_reviews(offer)
    if offer.user == current_user
      @reviews = []
    else
      @reviews = offer.reviews
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def my_bookings
    skip_authorization
    # I booked
    @make_bookings = current_user.bookings
  end

  def my_offers
    skip_authorization
    # all offers I made
    @offers = current_user.offers
    # I am booked by => offers I made, and booked by someone
    @booked_by = current_user.bookings_as_owner.where.not(user: current_user)
    # create new offer
    @offer = Offer.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @offer = Offer.find(params[:offer_id])
    @review = Review.new(review_params)
    @review.offer = @offer
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to offer_path(@offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to offer_path(@offer), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_about_me.html.erb
<div class="card-purple border-shadow-blue card-side">
  <%= cl_image_tag @offer.user.photo.key, { class: "avatar avatar-large position-middle", id: "avatar-aboutme" } %>
  <h2 class="position-middle mt-3"><%= @offer.user.name %></h2>
  <p class="position-middle">Greetings and thank you for visiting my profile! I enjoy gaming culture and connecting with people so let me help you reach your goals or get past that pesky boss fight that you've been stuck on!</p>
</div>

app/views/application/_big_card.html.erb
<div class="d-flex">
  <div class="m-3" style BACKGROUND>
    <h2 class="games-offered">Book Your Class</h2>
    <%= render 'game_card', offer: offer %>
    <div class="card-form justify-content-around align-items-top mt-3">
      <%= simple_form_for([@offer, @booking]) do |f| %>
        <div class="d-flex justify-content-around">
          <%= f.input :date, label: 'Choose Date', html5: true %>
          <%= f.submit 'Book Now', class: 'btn-blue d-flex justify-content-center' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/application/_booking_info.html.erb
<div class="booking-info">
  <div class="booking-info-title text-white">
    <%= booking.offer.game.name %>
  </div>
  <div class="booking-info-details text-white">
    Date: <%= booking.date %>
    <%= link_to 'X', booking_path(booking), data: { turbo_method: :delete, turbo_confirm: 'Delete?' }, class: "btn btn-primary"  %>
  </div>
</div>

app/views/application/_card_white_avatar.html.erb
<div class="position-relative ps-5">
  <div>
    <%= cl_image_tag user.photo.key, class: "avatar" %>
  </div>
  <div class="position-middle">
    <%= user.name %>
  </div>
</div>

app/views/application/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/application/_game_card.html.erb
<div class="card-offer mb-2">
  <%= link_to '', offer_path(offer), class: 'link-card' %>
  <img src=<%= offer.game.background_image %> />
  <div class="card-trip-infos d-flex justify-content-between">
    <div>
      <h2 class="card-user">
        <%= offer.game.name %>
      </h2>
    </div>
    <div class="card-user">
      <h2 class="card-trip-pricing d-flex justify-content-end">¥<%= number_with_delimiter(offer.price, delimiter: ",") %></h2>
      <h2 class="card-trip-pricing d-flex justify-content-end"><%= offer.duration %><%= offer.duration <= 1 ? "hr" : "hr".pluralize %></h2>
    </div>
  </div>
</div>

app/views/application/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to offers_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "text", id:"logo" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <div class="aisatsu">
          <p>Hello <%= current_user.email %>!</p>
        </div>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle m-2", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "I am a player", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "I am a coach", my_offers_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/application/_searchbar.html.erb
<div class="searchbar">
  <%= form_tag offers_path, method: :get, class: "d-flex search-form-control form-group" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Type game or coach's name"
      %>
    <button class='btn btn-primary' id="btn-search" style='width:40px;'>
      <i class="fas fa-search"></i>
    </button>
  <% end %>
</div>

app/views/application/_trio_card.html.erb
<div class="mt-4 me-3">
  <h5>Other <%= other_offers.count > 1 ? "Offers" : "Offer" %> :</h5>
  <% other_offers.each do |offer| %>
    <div class="card-trip mb-4 mt-3">
      <%= link_to '', offer_path(offer), class: 'link-card' %>
      <img src=<%= offer.game.background_image %> />
      <div class="card-trip-infos d-flex justify-content-between">
        <div>
          <h2 class="card-user">
            <%= offer.game.name %>
          </h2>
        </div>
        <div class="card-user">
          <p class="card-trip-pricing d-flex justify-content-end">¥<%= number_with_delimiter(offer.price, delimiter: ",") %></p>
          <p class="card-trip-pricing d-flex justify-content-end"><%= offer.duration %><%= offer.duration <= 1 ? "hr" : "hr".pluralize %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <title>PlayerWon</title>
    <%= favicon_link_tag %>
    <script src="https://kit.fontawesome.com/9305cf4a6e.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render "navbar" %>
    <%= render "flashes" %>
    <%= yield %>
  </body>
</html>

app/views/offers/backup.html.erb
<%# <div class="container"> <%# reviews %>
<h2><%= @reviews.count %> reviews (avg. <%= @reviews.average(:rating).to_i %>/5) </h2>
<% @reviews.each do |review| %>
  <div class="card-white d-flex p-2 mb-5">
    <%= render 'card_white_avatar', user: review.user %>
    <%= review.rating %>
    <%= review.content %>
    <% if review.in?(@my_reviews) %>
      <%= link_to 'x', review_path(review), data: { turbo_method: :delete, turbo_confirm: 'Delete?' }  %>
    <% end %>
    <br>
    <br>
  </div>
<% end %>
<%= simple_form_for([@offer, @review]) do |f| %>
  <div class="card-white d-flex p-2 mb-5">
    <%= render 'card_white_avatar', user: current_user %>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
    <%= f.input :content, placeholder: "Write a review" %>
    <%= f.submit %>
  </div>
<% end %>
<%# </div> %>

app/views/offers/index.html.erb
<%= render 'searchbar' %>
<div class="card-index">
  <% @offers.each do |offer| %>
    <div class="card-trip">
      <%= link_to '', offer_path(offer), class: 'link-card' %>
      <%= cl_image_tag offer.user.photo.key %>
      <div class="d-flex justify-content-between p-2 position-relative">
        <div>
          <h2><%= offer.user.name %></h2>
          <p class="p-2"><%= offer.game.name %></p>
        </div>
        <div class="card-user">
          <h2 class="d-flex justify-content-end">¥<%= number_with_delimiter(offer.price, delimiter: ",") %></h2>
          <h2 class="d-flex justify-content-end"><%= offer.duration %><%= offer.duration <= 1 ? "hr" : "hr".pluralize %></h2>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/offers/show.html.erb
<%= render 'searchbar' %>
<div class="row">
  <div class="col-12 col-sm-5 col-lg-3">
    <%= render 'about_me', offer: @offer %>
  </div>
  <div class="col-12 col-sm-7 col-lg-6">
    <%= render 'big_card', offer: @offer, booking: @booking %>
  </div>
  <div class="col-6 col-sm-6 col-lg-3">
    <%= render 'trio_card', other_offers: @other_offers %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="hero-image">
  <div class="d-flex justify-content-center">
    <img class="profilepic" src="/assets/yayaimg.jpg" alt="">
  </div>
</div>
<div class="container cards-dashboard d-flex">
  <div class="booked_by">
    <h2>I am booked by...</h2>
    <% if @booked_by == []  %>
      <h3>...you have no bookings...</h3>
    <% else %>
      <% @booked_by.each do |booking| %>
        <div class="card-product">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <div class="card-product-infos">
            Player name: <%= booking.user.name %>
            Game name: <%= booking.offer.game.name %>
            Date: <%= booking.date %>
            <% if booking.pending? %>
              <div class="d-flex">
                <%= simple_form_for booking do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
                  <%= f.submit 'Accept', class: 'btn btn-info' %>
                <% end %>
                <%= simple_form_for booking do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
                  <%= f.submit 'Reject', class: 'btn btn-light' %>
                <% end %>
              </div>
            <% else %>
              Status: <%= booking.status %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="booked_by">
    <h2>I have booked...</h2>
    <% if @make_bookings == []  %>
      <h3>...you have no bookings...</h3>
    <% else %>
      <% @make_bookings.each do |booking| %>
        <div class="card-product">
          <%# <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> %>
          <div class="card-product-infos">
            <%= booking.offer.user.name %> on
            <%= booking.offer.game.name %> on
            <%= link_to 'x', booking_path(booking), data: { turbo_method: :delete, turbo_confirm: 'Delete booking?' }  %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="booked_by">
    <h2>My Offerings</h2>
    <% if @offers == []  %>
      <h3>...you have no offerings...</h3>
    <% else %>
      <div class="card-product">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <%# <h2>Product name</h2>
        <p>Product description with <strong>relevant info</strong> only.</p> %>
          <ul>
            <% @offers.each do |offer| %>
              <li>
                <%= offer.game.name %>
                <%= distance_of_time_in_words(offer.duration*3600) %>
                <%= number_with_delimiter(offer.price, :delimiter => ',') %>¥
                <%= link_to 'x', offer_path(offer), data: { turbo_method: :delete, turbo_confirm: 'Delete offer?' }  %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.zdnet.com/a/img/resize/55a3891b942ccec51db2d4b31b9278e7acc4bc72/2022/03/25/e09d2790-b5bb-4523-b8b2-c09d9b98b85b/unnamed.png?auto=webp&width=1200);">
  <div class="container">
    <%= image_tag "logo.png", alt: "text", id: "hplogo"%>
    <h2>A Community Of Players Helping Players</h2>
    <div class="homesearch">
      <%= render "searchbar" %>
    </div>
  </div>
</div>
</div>

app/views/pages/my_bookings.html.erb
<div class="p-5 gap-5 d-flex justify-content-around">
  <div class="container border-blue border-shadow-blue">
    <h2>My Confirmed Bookings </h2>
    <% if @make_bookings == []  %>
      <h3>...you have no bookings...</h3>
    <% else %>
      <% @make_bookings.each do |booking| %>
        <% if booking.status == 'accepted' %>
          <div class="card-white d-flex p-2">
            <%= render 'card_white_avatar', user: booking.offer.user %>
            <%= render 'booking_info', booking: booking %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="container border-blue border-shadow-blue">
    <h2>My Pending Bookings</h2>
    <% if @make_bookings == []  %>
      <h3>...you have no bookings...</h3>
    <% else %>
      <% @make_bookings.each do |booking| %>
        <% if booking.status == 'pending' %>
          <div class="card-white d-flex p-2">
            <%= render 'card_white_avatar', user: booking.offer.user %>
            <%= render 'booking_info', booking: booking %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/my_offers.html.erb
<div class="p-5 gap-5 d-flex justify-content-around">
  <div class="container border-blue border-shadow-blue">
    <h2>My Coaching Requests</h2>
    <% if @booked_by == []  %>
      <h3>...you have no bookings...</h3>
    <% else %>
      <% @booked_by.each do |booking| %>
        <div class="card-white d-flex p-2">
          <%= render 'card_white_avatar', user: booking.user %>
          <%= render 'booking_info', booking: booking %>
          <div class="d-flex align-items-center">
            <% if booking.pending? %>
              <div class="d-flex">
                <%= simple_form_for booking do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
                  <%= f.submit 'Accept', class: 'btn btn-info mb-3' %>
                <% end %>
                <%= simple_form_for booking do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
                  <%= f.submit 'Reject', class: 'btn btn-light mb-3' %>
                <% end %>
              </div>
            <% else %>
              <p class='booking-tag'><%= booking.status %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="container card-purple border-shadow-blue">
    <div class="mb-5">
      <h2>Create A New Offer</h2>
      <%= simple_form_for(@offer, data: { turbo_confirm: "Are you sure ?"}) do |f| %>
        <%=f.input :game_id, collection: Game.all %>
        <%= f.input :price, label: "Price(¥)" %>
        <%= f.input :duration, label: "Duration(Hr)"%>
        <%= f.submit class: "btn-blue w-100"%>
      <% end %>
    </div>
    <h2>My Coaching Offers</h2>
    <% if @offers == []  %>
      <h3>...you have no offer...</h3>
    <% else %>
      <% @offers.each do |offer| %>
        <div class="card-product">
          <%= image_tag(offer.game.background_image) %>
          <div class="booking-info">
            <div class="booking-info-title">
              <%= offer.game.name %>
            </div>
            <div class="booking-info-details">
              <%= offer.duration %>h
              <%= number_with_delimiter(offer.price, :delimiter => ',') %>¥
            </div>
          </div>
          <% unless offer.bookings %>
            <%= link_to 'x', offer_path(offer), data: { turbo_method: :delete, turbo_confirm: 'Delete offer?' }  %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>